-- Personal Assistant Database Backup
-- Created: 2025-09-13T08:00:30.683640
-- Generated by Python backup method

-- Table: access_audit_logs
CREATE TABLE IF NOT EXISTS access_audit_logs (
    id integer NOT NULL DEFAULT nextval('access_audit_logs_id_seq'::regclass),
    user_id integer NOT NULL,
    resource_type character varying NOT NULL,
    resource_id integer NULL,
    action character varying NOT NULL,
    permission_granted boolean NOT NULL,
    roles_checked ARRAY NULL,
    ip_address inet NULL,
    user_agent text NULL,
    created_at timestamp without time zone NULL
);

-- Table: ai_tasks
CREATE TABLE IF NOT EXISTS ai_tasks (
    id integer NOT NULL DEFAULT nextval('ai_tasks_id_seq'::regclass),
    user_id integer NOT NULL,
    title character varying NOT NULL,
    description text NULL,
    task_type character varying NOT NULL,
    schedule_type character varying NOT NULL,
    schedule_config json NULL,
    next_run_at timestamp without time zone NULL,
    last_run_at timestamp without time zone NULL,
    status character varying NULL,
    ai_context text NULL,
    notification_channels ARRAY NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL
);

-- Table: auth_tokens
CREATE TABLE IF NOT EXISTS auth_tokens (
    id integer NOT NULL DEFAULT nextval('auth_tokens_id_seq'::regclass),
    user_id integer NOT NULL,
    token character varying NOT NULL,
    token_type character varying NULL,
    expires_at timestamp without time zone NOT NULL,
    is_revoked boolean NULL,
    created_at timestamp without time zone NULL,
    last_used_at timestamp without time zone NULL
);

-- Table: conversation_messages
CREATE TABLE IF NOT EXISTS conversation_messages (
    id integer NOT NULL DEFAULT nextval('conversation_messages_id_seq'::regclass),
    conversation_id character varying NOT NULL,
    role character varying NOT NULL,
    content text NULL,
    message_type character varying NULL,
    tool_name character varying NULL,
    tool_success character varying NULL,
    timestamp timestamp with time zone NULL DEFAULT now(),
    additional_data json NULL
);

-- Table: conversation_states
CREATE TABLE IF NOT EXISTS conversation_states (
    id integer NOT NULL DEFAULT nextval('conversation_states_id_seq'::regclass),
    conversation_id character varying NOT NULL,
    user_id integer NOT NULL,
    user_input text NULL,
    focus_areas json NULL,
    step_count integer NULL,
    last_tool_result json NULL,
    created_at timestamp with time zone NULL DEFAULT now(),
    updated_at timestamp with time zone NULL DEFAULT now()
);

-- Table: event_creation_logs
CREATE TABLE IF NOT EXISTS event_creation_logs (
    id integer NOT NULL DEFAULT nextval('event_creation_logs_id_seq'::regclass),
    user_id integer NULL,
    user_input text NULL,
    parsed_details json NULL,
    created_events integer NULL,
    errors text NULL,
    created_at timestamp without time zone NULL
);

-- Table: event_processing_log
CREATE TABLE IF NOT EXISTS event_processing_log (
    id integer NOT NULL DEFAULT nextval('event_processing_log_id_seq'::regclass),
    event_id integer NULL,
    processed_at timestamp without time zone NULL,
    agent_response text NULL,
    processing_status character varying NULL,
    error_message text NULL
);

-- Table: events
CREATE TABLE IF NOT EXISTS events (
    id integer NOT NULL DEFAULT nextval('events_id_seq'::regclass),
    user_id integer NULL,
    title character varying NULL,
    description character varying NULL,
    start_time timestamp without time zone NULL,
    end_time timestamp without time zone NULL,
    source character varying NULL,
    external_id character varying NULL,
    handled_at timestamp without time zone NULL,
    processing_status character varying NULL,
    agent_response text NULL,
    last_checked timestamp without time zone NULL,
    recurrence_pattern_id integer NULL,
    is_recurring boolean NULL,
    parent_event_id integer NULL,
    recurrence_instance_number integer NULL
);

-- Table: expense_categories
CREATE TABLE IF NOT EXISTS expense_categories (
    id integer NOT NULL DEFAULT nextval('expense_categories_id_seq'::regclass),
    name character varying NOT NULL
);

-- Table: expenses
CREATE TABLE IF NOT EXISTS expenses (
    id integer NOT NULL DEFAULT nextval('expenses_id_seq'::regclass),
    user_id integer NULL,
    amount numeric NULL,
    category_id integer NULL,
    description character varying NULL,
    created_at timestamp without time zone NULL
);

-- Table: grocery_analysis
CREATE TABLE IF NOT EXISTS grocery_analysis (
    id integer NOT NULL DEFAULT nextval('grocery_analysis_id_seq'::regclass),
    user_id integer NULL,
    analysis json NULL,
    created_at timestamp without time zone NULL
);

-- Table: grocery_deals
CREATE TABLE IF NOT EXISTS grocery_deals (
    id integer NOT NULL DEFAULT nextval('grocery_deals_id_seq'::regclass),
    source character varying NULL,
    title character varying NULL,
    price character varying NULL,
    image_url character varying NULL,
    flyer_date date NULL,
    created_at timestamp without time zone NULL
);

-- Table: grocery_items
CREATE TABLE IF NOT EXISTS grocery_items (
    id integer NOT NULL DEFAULT nextval('grocery_items_id_seq'::regclass),
    user_id integer NULL,
    name character varying NULL,
    quantity character varying NULL,
    added_at timestamp without time zone NULL
);

-- Table: ltm_contexts
CREATE TABLE IF NOT EXISTS ltm_contexts (
    id integer NOT NULL DEFAULT nextval('ltm_contexts_id_seq'::regclass),
    memory_id integer NOT NULL,
    context_type character varying NOT NULL,
    context_key character varying NOT NULL,
    context_value text NULL,
    confidence double precision NULL,
    created_at timestamp without time zone NULL
);

-- Table: ltm_memories
CREATE TABLE IF NOT EXISTS ltm_memories (
    id integer NOT NULL DEFAULT nextval('ltm_memories_id_seq'::regclass),
    user_id integer NOT NULL,
    content text NOT NULL,
    tags json NOT NULL,
    memory_type character varying NULL,
    category character varying NULL,
    importance_score integer NULL,
    confidence_score double precision NULL,
    dynamic_importance double precision NULL,
    context text NULL,
    context_data json NULL,
    source_type character varying NULL,
    source_id character varying NULL,
    created_by character varying NULL,
    created_at timestamp without time zone NULL,
    last_accessed timestamp without time zone NULL,
    last_modified timestamp without time zone NULL,
    access_count integer NULL,
    last_access_context text NULL,
    related_memory_ids json NULL,
    parent_memory_id integer NULL,
    memory_metadata json NULL,
    is_archived boolean NULL,
    archive_reason text NULL
);

-- Table: ltm_memory_access
CREATE TABLE IF NOT EXISTS ltm_memory_access (
    id integer NOT NULL DEFAULT nextval('ltm_memory_access_id_seq'::regclass),
    memory_id integer NOT NULL,
    access_timestamp timestamp without time zone NULL,
    access_context text NULL,
    access_method character varying NULL,
    user_query text NULL,
    was_relevant boolean NULL,
    relevance_score double precision NULL
);

-- Table: ltm_memory_relationships
CREATE TABLE IF NOT EXISTS ltm_memory_relationships (
    id integer NOT NULL DEFAULT nextval('ltm_memory_relationships_id_seq'::regclass),
    source_memory_id integer NOT NULL,
    target_memory_id integer NOT NULL,
    relationship_type character varying NOT NULL,
    strength double precision NULL,
    description text NULL,
    created_at timestamp without time zone NULL,
    last_accessed timestamp without time zone NULL
);

-- Table: ltm_memory_tags
CREATE TABLE IF NOT EXISTS ltm_memory_tags (
    id integer NOT NULL DEFAULT nextval('ltm_memory_tags_id_seq'::regclass),
    memory_id integer NOT NULL,
    tag_name character varying NOT NULL,
    tag_category character varying NULL,
    tag_importance double precision NULL,
    tag_confidence double precision NULL,
    usage_count integer NULL,
    first_used timestamp without time zone NULL,
    last_used timestamp without time zone NULL
);

-- Table: memory_context_items
CREATE TABLE IF NOT EXISTS memory_context_items (
    id integer NOT NULL DEFAULT nextval('memory_context_items_id_seq'::regclass),
    conversation_id character varying NOT NULL,
    source character varying NOT NULL,
    content text NULL,
    relevance_score double precision NULL,
    context_type character varying NULL,
    original_role character varying NULL,
    focus_area character varying NULL,
    preference_type character varying NULL,
    timestamp timestamp with time zone NULL DEFAULT now(),
    additional_data json NULL
);

-- Table: mfa_configurations
CREATE TABLE IF NOT EXISTS mfa_configurations (
    id integer NOT NULL DEFAULT nextval('mfa_configurations_id_seq'::regclass),
    user_id integer NOT NULL,
    totp_secret character varying NULL,
    totp_enabled boolean NULL,
    sms_enabled boolean NULL,
    phone_number character varying NULL,
    backup_codes json NULL,
    trusted_devices json NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL
);

-- Table: note_sync_log
CREATE TABLE IF NOT EXISTS note_sync_log (
    id integer NOT NULL DEFAULT nextval('note_sync_log_id_seq'::regclass),
    user_id integer NULL,
    note_id integer NULL,
    synced_at timestamp without time zone NULL,
    sync_status character varying NULL
);

-- Table: notes
CREATE TABLE IF NOT EXISTS notes (
    id integer NOT NULL DEFAULT nextval('notes_id_seq'::regclass),
    user_id integer NULL,
    title character varying NULL,
    content character varying NULL,
    created_at timestamp without time zone NULL,
    last_synced timestamp without time zone NULL
);

-- Table: permissions
CREATE TABLE IF NOT EXISTS permissions (
    id integer NOT NULL DEFAULT nextval('permissions_id_seq'::regclass),
    name character varying NOT NULL,
    resource_type character varying NOT NULL,
    action character varying NOT NULL,
    description text NULL,
    created_at timestamp without time zone NULL
);

-- Table: recurrence_patterns
CREATE TABLE IF NOT EXISTS recurrence_patterns (
    id integer NOT NULL DEFAULT nextval('recurrence_patterns_id_seq'::regclass),
    frequency character varying NOT NULL,
    interval integer NULL,
    weekdays ARRAY NULL,
    end_date timestamp without time zone NULL,
    max_occurrences integer NULL,
    created_at timestamp without time zone NULL
);

-- Table: reminders
CREATE TABLE IF NOT EXISTS reminders (
    id integer NOT NULL DEFAULT nextval('reminders_id_seq'::regclass),
    user_id integer NULL,
    message character varying NOT NULL,
    remind_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NULL,
    sent boolean NULL
);

-- Table: role_permissions
CREATE TABLE IF NOT EXISTS role_permissions (
    id integer NOT NULL DEFAULT nextval('role_permissions_id_seq'::regclass),
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    created_at timestamp without time zone NULL
);

-- Table: roles
CREATE TABLE IF NOT EXISTS roles (
    id integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
    name character varying NOT NULL,
    description text NULL,
    parent_role_id integer NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL
);

-- Table: security_events
CREATE TABLE IF NOT EXISTS security_events (
    id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass),
    user_id integer NULL,
    event_type character varying NOT NULL,
    event_data json NULL,
    severity character varying NULL,
    ip_address character varying NULL,
    user_agent text NULL,
    created_at timestamp without time zone NULL
);

-- Table: sms_router_configs
CREATE TABLE IF NOT EXISTS sms_router_configs (
    id integer NOT NULL DEFAULT nextval('sms_router_configs_id_seq'::regclass),
    config_key character varying NOT NULL,
    config_value text NOT NULL,
    description text NULL,
    is_active boolean NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL
);

-- Table: sms_usage_logs
CREATE TABLE IF NOT EXISTS sms_usage_logs (
    id integer NOT NULL DEFAULT nextval('sms_usage_logs_id_seq'::regclass),
    user_id integer NOT NULL,
    phone_number character varying NOT NULL,
    message_direction character varying NOT NULL,
    message_length integer NOT NULL,
    message_content text NULL,
    success boolean NULL,
    processing_time_ms integer NULL,
    error_message text NULL,
    country_code character varying NULL,
    sms_metadata json NULL,
    created_at timestamp without time zone NULL,
    retry_count integer NULL,
    max_retries integer NULL,
    next_retry_at timestamp without time zone NULL,
    twilio_message_sid character varying NULL,
    final_status character varying NULL
);

-- Table: task_results
CREATE TABLE IF NOT EXISTS task_results (
    id integer NOT NULL DEFAULT nextval('task_results_id_seq'::regclass),
    task_id integer NULL,
    result json NULL,
    completed_at timestamp without time zone NULL
);

-- Table: tasks
CREATE TABLE IF NOT EXISTS tasks (
    id integer NOT NULL DEFAULT nextval('tasks_id_seq'::regclass),
    user_id integer NULL,
    task_name character varying NULL,
    status character varying NULL,
    scheduled_at timestamp without time zone NULL,
    created_at timestamp without time zone NULL
);

-- Table: todos
CREATE TABLE IF NOT EXISTS todos (
    id integer NOT NULL DEFAULT nextval('todos_id_seq'::regclass),
    user_id integer NOT NULL,
    title character varying NOT NULL,
    description text NULL,
    due_date timestamp without time zone NULL,
    done_date timestamp without time zone NULL,
    priority character varying NULL,
    category character varying NULL,
    status character varying NULL,
    missed_count integer NOT NULL,
    last_missed_at timestamp without time zone NULL,
    is_segmented boolean NOT NULL,
    parent_task_id integer NULL,
    segmentation_triggered_at timestamp without time zone NULL,
    completion_patterns jsonb NULL,
    user_insights jsonb NULL,
    segmentation_suggestions jsonb NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL
);

-- Table: user_phone_mappings
CREATE TABLE IF NOT EXISTS user_phone_mappings (
    id integer NOT NULL DEFAULT nextval('user_phone_mappings_id_seq'::regclass),
    user_id integer NOT NULL,
    phone_number character varying NOT NULL,
    is_primary boolean NULL,
    is_verified boolean NULL,
    verification_method character varying NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL
);

-- Table: user_roles
CREATE TABLE IF NOT EXISTS user_roles (
    id integer NOT NULL DEFAULT nextval('user_roles_id_seq'::regclass),
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    is_primary boolean NULL,
    granted_by integer NULL,
    granted_at timestamp without time zone NULL,
    expires_at timestamp without time zone NULL
);

-- Table: user_sessions
CREATE TABLE IF NOT EXISTS user_sessions (
    id integer NOT NULL DEFAULT nextval('user_sessions_id_seq'::regclass),
    user_id integer NOT NULL,
    session_id character varying NOT NULL,
    device_info json NULL,
    ip_address character varying NULL,
    user_agent text NULL,
    created_at timestamp without time zone NULL,
    last_accessed timestamp without time zone NULL,
    expires_at timestamp without time zone NOT NULL,
    is_active boolean NULL
);

-- Table: user_settings
CREATE TABLE IF NOT EXISTS user_settings (
    id integer NOT NULL DEFAULT nextval('user_settings_id_seq'::regclass),
    user_id integer NOT NULL,
    key character varying NOT NULL,
    value text NULL,
    setting_type character varying NOT NULL,
    is_public boolean NULL,
    validation_rules json NULL,
    category character varying NULL,
    description text NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL
);

-- Table: users
CREATE TABLE IF NOT EXISTS users (
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    email character varying NOT NULL,
    phone_number character varying NULL,
    full_name character varying NULL,
    hashed_password character varying NOT NULL,
    is_active boolean NULL,
    is_verified boolean NULL,
    verification_token character varying NULL,
    password_reset_token character varying NULL,
    password_reset_expires timestamp without time zone NULL,
    last_login timestamp without time zone NULL,
    failed_login_attempts integer NULL,
    locked_until timestamp without time zone NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL,
    default_role_id integer NULL,
    role_assigned_at timestamp without time zone NULL,
    role_assigned_by integer NULL
);

-- Data for table users
INSERT INTO users VALUES (1, 'ian.le.blanc@hotmail.com', '4388290590', 'Ian Le Blanc', '$2b$12$4645b7hoLC.zxlSHQwgetO4BYr7wkjXVZhQ7jjPNqVNjy4ygtQ/lu', True, False, 'XchViNp591bGW3Q243_lCFlaOR4EPvevAcUkgyx8Qa8', NULL, NULL, NULL, 0, NULL, 2025-09-13 11:59:20.990987, 2025-09-13 11:59:20.990991, NULL, NULL, NULL);
