version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ianleblanc"
    assignees:
      - "ianleblanc"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/src/apps/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ianleblanc"
    assignees:
      - "ianleblanc"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ianleblanc"
    assignees:
      - "ianleblanc"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ianleblanc"
    assignees:
      - "ianleblanc"
    commit-message:
      prefix: "chore"
      include: "scope"
