[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["personal_assistant", "apps"]
known_third_party = ["fastapi", "pydantic", "sqlalchemy", "redis", "celery"]
skip_glob = ["**/migrations/*.py"]

[tool.mypy]
# Ignore missing imports for external libraries
ignore_missing_imports = true

# Additional mypy configuration
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

# Exclude migration files and test files from strict checking
exclude = [
    ".*/migrations/.*\\.py$",
    ".*/tests/.*\\.py$",
    ".*/test_.*\\.py$"
]
