"""
FastAPI application models package.

This package contains Pydantic models for API requests and responses.
"""

from .conversation import (
    ConversationListResponse,
    ConversationMessageCreateRequest,
    ConversationMessageResponse,
    ConversationSearchRequest,
    ConversationStateCreateRequest,
    ConversationStateResponse,
    ConversationStateUpdateRequest,
    MemoryContextItemCreateRequest,
    MemoryContextItemResponse,
)
from .ltm_memory import (
    LTMContextResponse,
    LTMMemoryAccessResponse,
    LTMMemoryCreateRequest,
    LTMMemoryListResponse,
    LTMMemoryResponse,
    LTMMemorySearchRequest,
    LTMMemoryTagResponse,
    LTMMemoryUpdateRequest,
)
from .mfa import (
    MFAConfigurationCreateRequest,
    MFAConfigurationResponse,
    MFAConfigurationUpdateRequest,
    MFASetupResponse,
    MFAVerifyRequest,
    MFAVerifyResponse,
    SecurityEventCreateRequest,
    SecurityEventListResponse,
    SecurityEventResponse,
    SecurityEventSearchRequest,
    SecurityEventUpdateRequest,
    UserSessionCreateRequest,
    UserSessionListResponse,
    UserSessionResponse,
    UserSessionSearchRequest,
)
from .phone_management import (
    PhoneNumberBase,
    PhoneNumberCreate,
    PhoneNumberDeleteResponse,
    PhoneNumberListResponse,
    PhoneNumberResponse,
    PhoneNumberUpdate,
    PhoneNumberVerificationCode,
    PhoneNumberVerificationRequest,
    PhoneNumberVerificationResponse,
)
from .rbac import (
    AccessAuditLogCreateRequest,
    AccessAuditLogListResponse,
    AccessAuditLogResponse,
    AccessAuditLogSearchRequest,
    PermissionCreateRequest,
    PermissionListResponse,
    PermissionResponse,
    PermissionSearchRequest,
    RoleCreateRequest,
    RoleListResponse,
    RolePermissionCreateRequest,
    RolePermissionResponse,
    RoleResponse,
    RoleSearchRequest,
    RoleUpdateRequest,
    UserRoleCreateRequest,
    UserRoleListResponse,
    UserRoleResponse,
)
from .users import (
    UserCreateRequest,
    UserDeleteRequest,
    UserListResponse,
    UserPreferencesResponse,
    UserPreferencesUpdateRequest,
    UserPublicResponse,
    UserResponse,
    UserUpdateRequest,
)

__all__ = [
    # User models
    "UserResponse",
    "UserPublicResponse",
    "UserUpdateRequest",
    "UserPreferencesResponse",
    "UserPreferencesUpdateRequest",
    "UserListResponse",
    "UserCreateRequest",
    "UserDeleteRequest",
    # Phone management models
    "PhoneNumberBase",
    "PhoneNumberCreate",
    "PhoneNumberUpdate",
    "PhoneNumberResponse",
    "PhoneNumberListResponse",
    "PhoneNumberVerificationRequest",
    "PhoneNumberVerificationCode",
    "PhoneNumberVerificationResponse",
    "PhoneNumberDeleteResponse",
    # LTM Memory models
    "LTMMemoryResponse",
    "LTMMemoryCreateRequest",
    "LTMMemoryUpdateRequest",
    "LTMMemoryListResponse",
    "LTMMemorySearchRequest",
    "LTMContextResponse",
    "LTMMemoryTagResponse",
    "LTMMemoryAccessResponse",
    # Conversation models
    "ConversationStateResponse",
    "ConversationStateCreateRequest",
    "ConversationStateUpdateRequest",
    "ConversationMessageResponse",
    "ConversationMessageCreateRequest",
    "MemoryContextItemResponse",
    "MemoryContextItemCreateRequest",
    "ConversationListResponse",
    "ConversationSearchRequest",
    # RBAC models
    "RoleResponse",
    "RoleCreateRequest",
    "RoleUpdateRequest",
    "PermissionResponse",
    "PermissionCreateRequest",
    "RolePermissionResponse",
    "RolePermissionCreateRequest",
    "UserRoleResponse",
    "UserRoleCreateRequest",
    "AccessAuditLogResponse",
    "AccessAuditLogCreateRequest",
    "RoleListResponse",
    "PermissionListResponse",
    "UserRoleListResponse",
    "AccessAuditLogListResponse",
    "RoleSearchRequest",
    "PermissionSearchRequest",
    "AccessAuditLogSearchRequest",
    # MFA models
    "MFAConfigurationResponse",
    "MFAConfigurationCreateRequest",
    "MFAConfigurationUpdateRequest",
    "UserSessionResponse",
    "UserSessionCreateRequest",
    "SecurityEventResponse",
    "SecurityEventCreateRequest",
    "SecurityEventUpdateRequest",
    "MFASetupResponse",
    "MFAVerifyRequest",
    "MFAVerifyResponse",
    "UserSessionListResponse",
    "SecurityEventListResponse",
    "UserSessionSearchRequest",
    "SecurityEventSearchRequest",
]
