auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  allow_structured_metadata: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

ruler:
  alertmanager_url: http://localhost:9093

# Remove outdated fields that were causing errors
# compactor:
#   working_directory: /tmp/loki/boltdb-shipper-compactor
#   shared_store: filesystem  # This field no longer exists

# limits_config:
#   enforce_metric_name: false  # This field no longer exists
#   reject_old_samples: true
#   reject_old_samples_max_age: 168h

# chunk_store_config:
#   max_look_back_period: 0s  # This field no longer exists

analytics:
  reporting_enabled: false
