global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Personal Assistant API
  - job_name: "personal_assistant_api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: "/health/database/performance"
    scrape_interval: 30s

  # PostgreSQL Database
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    # Note: Requires postgres_exporter for actual metrics

  # Redis
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    # Note: Requires redis_exporter for actual metrics

  # Node Exporter (if running on host)
  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]
    # Note: Requires node_exporter to be running on host
